### ISSUE TITLE
TypeScript types 

### ISSUE THREAD

**Issue by kiwikern** [jehy/telegram-test-api#12]
It'd be great if the library had type definitions so that it can easily be used with TypeScript.

I've created a type definition myself but it's probably not completely correct, see [gist](https://gist.github.com/kiwikern/b20b2473db322e6ab2b3bf2bc936bf62).

**Comment by jehy** [comment]
I'm not a fan of Typescript but I would gladly accept PR. It can be incomplete, but it should be better then nothing : )

**Comment by kiwikern** [comment]
Great thanks. :-) Hopefully, it's a start and other people will start improving it along the way. :-)

**Comment by jehy** [comment]
Merged: )
