### ISSUE TITLE
Compatability with jest

### ISSUE THREAD

**Issue by kiwikern** [jehy/telegram-test-api#13]
When I import `'telegram-test-api'` in a jest test it will fail with `Unable to expose method "then"`.

    import * as TelegramServer from 'telegram-test-api';

Apparently, this is because jest is not compatible with `request-promise`, see this [issue](https://github.com/request/request-promise/issues/247).

As a workaround, you can mock out `request-promise` before the import, but then of course the requests won't work.

    jest.mock('request-promise-native');

**Comment by jehy** [comment]
Could you provide me with an example and with full stack trace? I just replaced mocha with jest for package's internal tests and everything went fine.

**Comment by jehy** [comment]
By the way, try version 2.0.0 - I just published it. It has axios instead of request-promise as a dependency, so it can help.

**Comment by kiwikern** [comment]
Great! :-) Thank you!
