### ISSUE TITLE
Is there support for callback queries

### ISSUE THREAD

**Issue by tigermarques** [jehy/telegram-test-api#18]
Hi,

I'm testing a bot which has the following sequence of steps:
1. the user sends a /start command
2. the bot sends a list of options with telegram buttons
3. the user presses a button with the chosen option

I've been able to test the first two steps, but I'm not sure if either the makeMessage or makeCommand methods are suitable to send a message as if the user had pressed one of the buttons.

Is this possible with the existing methods? Or how could I tackle this issue?

Thank you!

**Comment by tigermarques** [comment]
I've digged around the code for a bit, and it seems that in `routes/bot/getUpdates.js`, the `getUpdates` method is forcing all messages received by the the bot to be in the format
```
{
  update_id: 'xxx',
  message: {
    ...
  }
}

However, for a callback_query, the actual format is
```
{
  update_id: 'xxx',
  callback_query: {
    ...
  }
}
```

I think that it might be possible to support this, but maybe the client must be able to send the message in a format, and the bot receive it in the same format.

What do you think?

**Comment by jehy** [comment]
check https://github.com/jehy/telegram-test-api/pull/24 - simple support for callback queries was added.

**Comment by jehy** [comment]
Should be closed via https://github.com/jehy/telegram-test-api/pull/49
